 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/blog_categories", type: :request do
  # BlogCategory. As you add validations to BlogCategory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      BlogCategory.create! valid_attributes
      get blog_categories_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      blog_category = BlogCategory.create! valid_attributes
      get blog_category_url(blog_category)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_blog_category_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      blog_category = BlogCategory.create! valid_attributes
      get edit_blog_category_url(blog_category)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new BlogCategory" do
        expect {
          post blog_categories_url, params: { blog_category: valid_attributes }
        }.to change(BlogCategory, :count).by(1)
      end

      it "redirects to the created blog_category" do
        post blog_categories_url, params: { blog_category: valid_attributes }
        expect(response).to redirect_to(blog_category_url(BlogCategory.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new BlogCategory" do
        expect {
          post blog_categories_url, params: { blog_category: invalid_attributes }
        }.to change(BlogCategory, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post blog_categories_url, params: { blog_category: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested blog_category" do
        blog_category = BlogCategory.create! valid_attributes
        patch blog_category_url(blog_category), params: { blog_category: new_attributes }
        blog_category.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the blog_category" do
        blog_category = BlogCategory.create! valid_attributes
        patch blog_category_url(blog_category), params: { blog_category: new_attributes }
        blog_category.reload
        expect(response).to redirect_to(blog_category_url(blog_category))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        blog_category = BlogCategory.create! valid_attributes
        patch blog_category_url(blog_category), params: { blog_category: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested blog_category" do
      blog_category = BlogCategory.create! valid_attributes
      expect {
        delete blog_category_url(blog_category)
      }.to change(BlogCategory, :count).by(-1)
    end

    it "redirects to the blog_categories list" do
      blog_category = BlogCategory.create! valid_attributes
      delete blog_category_url(blog_category)
      expect(response).to redirect_to(blog_categories_url)
    end
  end
end
